#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

const decksDir = path.join(__dirname, '..', 'content', 'decks')
const outputDir = path.join(__dirname, '..', 'src', 'generated')

function getGitLastModified(filePath) {
  try {
    const timestamp = execSync(`git log -1 --format=%cI -- "${filePath}"`, {
      encoding: 'utf8',
    }).trim()
    return timestamp || null
  } catch {
    return null
  }
}

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true })
}

// Process all markdown files in decks directory
const files = fs.readdirSync(decksDir).filter((f) => f.endsWith('.md'))

const allDates = {}

for (const file of files) {
  const slug = file.replace(/\.md$/, '')
  const filePath = path.join(decksDir, file)
  const lastEdited = getGitLastModified(filePath)

  if (lastEdited) {
    allDates[slug] = lastEdited
    console.log(`Got date for ${slug}: ${lastEdited}`)
  }
}

// Write the dates data as a TypeScript file
const outputPath = path.join(outputDir, 'deck-dates.ts')
const tsContent = `// This file is auto-generated by scripts/generate-dates.js
// Do not edit manually

export type DeckDates = Record<string, string>

export const deckDates: DeckDates = ${JSON.stringify(allDates, null, 2)}
`

fs.writeFileSync(outputPath, tsContent)
console.log(`\nWrote dates data to ${outputPath}`)
console.log('Done generating deck dates')
